window.SITE_DEFAULT_CONTENT = {
    translations: {
        en: {
            brandName: "EMA SOFT",
            navServices: "Services",
            navPortfolio: "Portfolio",
            navAbout: "About",
            navContact: "Get in touch",
            lightMode: "Light mode",
            darkMode: "Dark mode",
            heroLead: "We build",
            heroEmphasis: "smart software",
            heroTail: "for growing businesses.",
            heroDescription: "EMA SOFT delivers modern web, mobile, and cloud solutions tailored to your business needs, with a focus on performance, scalability, and clean user experience.",
            heroServices: "Explore services",
            heroPortfolio: "View portfolio",
            heroBadge: "Trusted by small & medium businesses in the region.",
            heroTagline: "Technology-driven solutions with a focus on UI/UX and reliability.",
            servicesTitle: "Services",
            servicesIntro: "Core solutions we provide to help your business grow.",
            portfolioTitle: "Portfolio",
            portfolioIntro: "Selected projects showcasing our capabilities.",
            aboutTitle: "About EMA SOFT",
            aboutIntro: "Who we are and how we work.",
            aboutParagraphOne: "EMA SOFT is a software company focused on delivering practical, well-designed digital solutions for businesses that want to grow and modernize their operations.",
            aboutParagraphTwo: "We combine strong technical foundations with attention to UI/UX, ensuring that every product is not only powerful, but also easy and pleasant to use.",
            aboutHighlight: "Our approach: understand the business, design the experience, build the technology, and support it long-term.",
            aboutWhy: "Why clients choose us:",
            aboutReasonOne: "Clear communication and transparent process",
            aboutReasonTwo: "Focus on performance and reliability",
            aboutReasonThree: "Tailored solutions, not generic templates",
            aboutReasonFour: "Long-term partnership mindset",
            copyright: "© EMA SOFT – All rights reserved.",
            adminDashboard: "Admin",
            whatsappLink: "WhatsApp",
            whatsappOpen: "Open WhatsApp chat",
            whatsappNoticeLabel: "New message from EMA SOFT. Open WhatsApp chat.",
            whatsappNoticeTitle: "New message from EMA SOFT",
            whatsappNoticeText: "Hello there! How can we help?",
            chatReply: "Typically replies within 1 hour",
            chatClose: "Close chat",
            chatGreeting: "Hello there! 👋",
            chatQuestion: "How can we help?",
            chatTime: "Just now ✓✓",
            chatPlaceholder: "Type a message...",
            chatSend: "Send message"
        },
        ar: {
            brandName: "EMA SOFT",
            navServices: "خدماتنا",
            navPortfolio: "أعمالنا",
            navAbout: "من نحن",
            navContact: "تواصل معنا",
            lightMode: "الوضع النهاري",
            darkMode: "الوضع الليلي",
            heroLead: "نصمم",
            heroEmphasis: "برمجيات ذكية",
            heroTail: "لنمو أعمالك.",
            heroDescription: "تقدم EMA SOFT حلولاً حديثة للويب والهواتف والسحابة، مصممة لتناسب احتياجات أعمالك، مع التركيز على الأداء وقابلية التوسع وتجربة استخدام سلسة.",
            heroServices: "اكتشف خدماتنا",
            heroPortfolio: "تصفح أعمالنا",
            heroBadge: "محل ثقة الشركات الصغيرة والمتوسطة في المنطقة.",
            heroTagline: "حلول تقنية تركز على تجربة المستخدم والموثوقية.",
            servicesTitle: "خدماتنا",
            servicesIntro: "حلولنا الأساسية لمساعدتك على تنمية أعمالك.",
            portfolioTitle: "أعمالنا",
            portfolioIntro: "نماذج مختارة من المشاريع التي تعكس خبراتنا.",
            aboutTitle: "عن EMA SOFT",
            aboutIntro: "من نحن وكيف نعمل.",
            aboutParagraphOne: "EMA SOFT شركة برمجيات تهتم بتقديم حلول رقمية عملية ومدروسة للشركات التي تسعى إلى النمو وتطوير عملياتها.",
            aboutParagraphTwo: "نجمع بين الأسس التقنية القوية والاهتمام بتجربة المستخدم، لنضمن أن يكون كل منتج فعالاً وسهل الاستخدام في الوقت نفسه.",
            aboutHighlight: "منهجنا: نفهم نشاطك، ونصمم التجربة، ونبني التقنية، ثم نواصل دعمك على المدى الطويل.",
            aboutWhy: "لماذا يختارنا عملاؤنا؟",
            aboutReasonOne: "تواصل واضح وخطوات عمل شفافة",
            aboutReasonTwo: "تركيز على الأداء والموثوقية",
            aboutReasonThree: "حلول مصممة لاحتياجاتك وليست قوالب جاهزة",
            aboutReasonFour: "شراكة طويلة الأمد",
            copyright: "© EMA SOFT – جميع الحقوق محفوظة.",
            adminDashboard: "لوحة التحكم",
            whatsappLink: "واتساب",
            whatsappOpen: "فتح محادثة واتساب",
            whatsappNoticeLabel: "رسالة جديدة من EMA SOFT. افتح محادثة واتساب.",
            whatsappNoticeTitle: "رسالة جديدة من EMA SOFT",
            whatsappNoticeText: "أهلاً بيك! كيف نقدر نساعدك؟",
            chatReply: "نرد عادة خلال ساعة",
            chatClose: "إغلاق المحادثة",
            chatGreeting: "أهلاً بيك! 👋",
            chatQuestion: "كيف نقدر نساعدك؟",
            chatTime: "الآن ✓✓",
            chatPlaceholder: "اكتب رسالة...",
            chatSend: "إرسال الرسالة"
        }
    },
    services: [
        { id: "web", icon: "🌐", title: { en: "Web Development", ar: "تطوير المواقع" }, description: { en: "Responsive, fast, and secure websites built with modern technologies.", ar: "مواقع سريعة وآمنة ومتوافقة مع مختلف الأجهزة، مبنية بأحدث التقنيات." } },
        { id: "mobile", icon: "📱", title: { en: "Mobile Apps", ar: "تطبيقات الهواتف" }, description: { en: "Cross-platform mobile applications with smooth user experience.", ar: "تطبيقات متعددة المنصات بتجربة استخدام سلسة." } },
        { id: "design", icon: "🎨", title: { en: "UI/UX Design", ar: "تصميم UI/UX" }, description: { en: "Clean, intuitive interfaces focused on usability and clarity.", ar: "واجهات واضحة وسهلة الاستخدام تركز على الوضوح والفاعلية." } },
        { id: "cloud", icon: "☁️", title: { en: "Cloud Solutions", ar: "الحلول السحابية" }, description: { en: "Scalable backend and cloud infrastructure for your applications.", ar: "أنظمة خلفية وبنية سحابية قابلة للتوسع لتطبيقاتك." } },
        { id: "automation", icon: "⚙️", title: { en: "Automation", ar: "الأتمتة" }, description: { en: "Automating workflows to save time and reduce manual work.", ar: "أتمتة سير العمل لتوفير الوقت وتقليل المهام اليدوية." } },
        { id: "support", icon: "🛠️", title: { en: "Technical Support", ar: "الدعم الفني" }, description: { en: "Ongoing maintenance, monitoring, and support for your systems.", ar: "صيانة ومراقبة ودعم مستمر لأنظمتك." } }
    ],
    projects: [
        { id: "dashboard", title: { en: "Business Management Dashboard", ar: "لوحة إدارة الأعمال" }, tag: { en: "Web App · Analytics", ar: "تطبيق ويب · تحليلات" } },
        { id: "commerce", title: { en: "E-commerce Platform", ar: "منصة تجارة إلكترونية" }, tag: { en: "Web · Payments", ar: "ويب · مدفوعات" } },
        { id: "booking", title: { en: "Service Booking App", ar: "تطبيق حجز الخدمات" }, tag: { en: "Mobile · UI/UX", ar: "هواتف · تجربة المستخدم" } }
    ],
    contact: {
        email: "info@emasoft.com",
        whatsapp: "971543745749"
    }
};
